import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/ui/organisms/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<nav className="fixed start-0 top-0 z-20 h-20 w-full border-b border-gray-200 bg-white shadow-md dark:border-gray-600 dark:bg-gray-900">
					<Navbar />
				</nav>
				<main className="mt-20 flex min-h-[calc(100vh-160px)] flex-col items-center justify-between dark:bg-gray-900">
					{children}
				</main>
				<footer className="flex h-20 items-center justify-center  bg-gray-900">
					<p className="mx-auto  text-center text-gray-400">© Ireneusz Cisło</p>
				</footer>
			</body>
		</html>
	);
}
